<a href="https://colab.research.google.com/github/Shamana027/Linear_Algebra_ChE_2nd-sem-2020-2021/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Assignment 3 : Matrices


### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.



# Discussion


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


## Matrices

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\ 
C = \left\{
    \begin{array}\
          w-2x+3y-5z \\
          3w-x-2y+z \\
          2w-x+3y-2z \\
    \end{array}\
  \right. \\ $$

$$
A=\begin{bmatrix} 3 & -1 \\ 6 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 3 & 2 & 1 \\ -3 & -2 & -1 \\ 7 & 2 & 5\end{bmatrix}\\
C=\begin{bmatrix} 4 & -1 & -2 & 3 \\ 6 & 2 & -2 & 4 \\ -3 & 5 & -4 & 1\end{bmatrix}
$$

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_matrix(matrix):
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
A = np.array([
    [5, 3],
    [4, 2]
])
describe_matrix(A)

Matrix:
[[5 3]
 [4 2]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1,2,3],
    [2,3,4]
])
describe_matrix(G)


Matrix:
[[1 2 3]
 [2 3 4]]

Shape:	(2, 3)
Rank:	2



In [ ]:
B = np.array([
    [5, 5],
    [3, 7],
    [2, 8]
])
describe_matrix(B)


Matrix:
[[5 5]
 [3 7]
 [2 8]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([5, 10, 15, 20])
describe_matrix(H)


Matrix:
[ 5 10 15 20]

Shape:	(4,)
Rank:	1



# Categorizing Matrices

## According to shape



### Row and Column Matrices

In [ ]:
rowmatrix1D = np.array([
    -4, 1, -3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [7, 5, 3, 1]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_matrix(rowmatrix1D)
describe_matrix(row_mat_2D)


Matrix:
[-4  1 -3  2]

Shape:	(4,)
Rank:	1

Matrix:
[[7 5 3 1]]

Shape:	(1, 4)
Rank:	2



In [ ]:
col_mat = np.array([
    [7],
    [4],
    [1]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_matrix(col_mat)


Matrix:
[[7]
 [4]
 [1]]

Shape:	(3, 1)
Rank:	2



### Square Matrices

In [ ]:
def describe_matrix(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [7,3,1],
    [4,4,4],
    [9,0,3]
])

non_square_mat = np.array([
    [11,22,33],
    [77,88,99]
])
describe_matrix(square_mat)
describe_matrix(non_square_mat)


Matrix:
[[7 3 1]
 [4 4 4]
 [9 0 3]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[11 22 33]
 [77 88 99]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## According to element values

### Null Matrix


In [ ]:
def describe_matrix(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_mat = np.array([[]])
describe_matrix(null_mat)


Matrix is Null


In [ ]:
null_mat = np.array([[1]])
describe_matrix(null_mat)


Matrix:
[[1]]

Shape:	(1, 1)
Rank:	2
Is Square: True



### Zero Matrix

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Ones Matrix

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Diagonal Matrix

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])


array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([1,1,1])
d

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Identity Matrix

In [ ]:
np.identity(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Upper Triangular Matrix

In [ ]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [ ]:
F = np.array([
                      [5, 4, 3, 2, 1],
                      [5, 4, 3, 2, 1],
                      [5, 4, 3, 2, 1],
                      [5, 4, 3, 2, 1],
                      [5, 4, 3, 2, 1],
])
np.triu(F)

array([[5, 4, 3, 2, 1],
       [0, 4, 3, 2, 1],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 2, 1],
       [0, 0, 0, 0, 1]])

### Lower Triangular Matrix

In [ ]:
np.tril(F)

array([[5, 0, 0, 0, 0],
       [5, 4, 0, 0, 0],
       [5, 4, 3, 0, 0],
       [5, 4, 3, 2, 0],
       [5, 4, 3, 2, 1]])

# Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


2. 2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])
G

array([[1, 7, 8],
       [2, 2, 2],
       [4, 6, 7]])

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

## Matrix Algebra

### Addition

In [ ]:
A = np.array([
              [1,3],
              [5,7],
              [9,11]
])
B = np.array([
              [0,2],
              [4,6],
              [8,10]
])
A+B

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [ ]:
3+B

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

### Subtraction

In [ ]:
A-B

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
3-A

array([[ 2,  0],
       [-2, -4],
       [-6, -8]])

### Element-wise Multiplication

In [ ]:
A*B
np.multiply(A,B)


array([[  0,   6],
       [ 20,  42],
       [ 72, 110]])

In [ ]:
2*B

array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[1.00000000e+10, 1.50000000e+00],
       [1.25000000e+00, 1.16666667e+00],
       [1.12500000e+00, 1.10000000e+00]])

In [ ]:
np.add(A,B)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

## Activity

# Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

def mat_desc(matrix):
    a = np.zeros(((4,4)),dtype=int) 
    b = np.ones(((4,4)),dtype=int)
    c = np.diag([1,1,1,1])
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        is_zero = True if ((matrix == a ).all()) else False 
        is_one = True if ((matrix == b ).all()) else False
        is_identity = True if((matrix == c ).all()) else False 

        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare: {is_square}\nZero: {is_zero}\nOne: {is_one}\nIdentity: {is_identity}\n')    
    else:
        print('Matrix is Null')

In [ ]:
q = np.array([
      [4,7,2,5],
      [2,5,5,3],
      [1,9,3,8],
      [7,4,7,4]
])

w = np.array([
      [1,0,0,0],
      [0,1,0,0],
      [0,0,1,0],
      [0,0,0,1]
])

e = np.array([
      [1,1,1,1],
      [1,1,1,1],
      [1,1,1,1],
      [1,1,1,1]
])

r = np.array([
      [0,0,0,0],
      [0,0,0,0],
      [0,0,0,0],
      [0,0,0,0]
])

t = np.array([])

In [ ]:
mat_desc(q)
mat_desc(w)
mat_desc(e)
mat_desc(r)
mat_desc(t)

Matrix:
[[4 7 2 5]
 [2 5 5 3]
 [1 9 3 8]
 [7 4 7 4]]

Shape:	(4, 4)
Rank:	2
Square: True
Zero: False
One: False
Identity: False

Matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Shape:	(4, 4)
Rank:	2
Square: True
Zero: False
One: False
Identity: True

Matrix:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Shape:	(4, 4)
Rank:	2
Square: True
Zero: False
One: True
Identity: False

Matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Shape:	(4, 4)
Rank:	2
Square: True
Zero: True
One: False
Identity: False

Matrix is Null


## Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

def mat_operations(matrix):    
      
      print(f'Matrix:\n{matrix}')

In [ ]:
A = np.array([
               [1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [1, 0, 2]
])
B = np.array([
               [3, 1, 2],
               [6, 5, 4],
               [8, 9, 7],
               [9, 5, 3]
])
C = np.array([
               [8, 5, 5],
               [9, 6, 2],
               [5, 4, 3],
               [2, 3, 6]
])
D = np.array([
               [5, 3, 7, 9],
               [2, 7, 3, 7],
               [9, 4, 3, 6],
               [2, 2, 3, 2],
               [5, 4, 3, 2]
])
E = np.array([
               [9, 4, 1, 7, 1],
               [6, 3, 3, 1, 2],
               [7, 4, 9, 2, 3],
               [3, 7, 9, 3, 4]
])

In [ ]:
try:  
      mat_operations(A*C)
except ValueError:
      print("1. Matrix is not viable\n")
else:
      print("1. Matrix is viable\n")

try:  
      mat_operations(A-B)
except ValueError:
      print("2. Matrix is not viable\n")
else:
      print("2. Matrix is viable\n")

try:  
      mat_operations(D*E)
except ValueError:
      print("3. Matrix is not viable\n")
else:
      print("3. Matrix is viable\n")

try:  
      mat_operations(A/B)
except ValueError:
      print("4. Matrix is not viable\n")
else:
      print("4. Matrix is viable\n")

try:  
      mat_operations(A+B)
except ValueError:
      print("5. Matrix is not viable\n")
else:
      print("5. Matrix is viable\n")


Matrix:
[[ 8 10 15]
 [36 30 12]
 [35 32 27]
 [ 2  0 12]]
1. Matrix is viable

Matrix:
[[-2  1  1]
 [-2  0  2]
 [-1 -1  2]
 [-8 -5 -1]]
2. Matrix is viable

3. Matrix is not viable

Matrix:
[[0.33333333 2.         1.5       ]
 [0.66666667 1.         1.5       ]
 [0.875      0.88888889 1.28571429]
 [0.11111111 0.         0.66666667]]
4. Matrix is viable

Matrix:
[[ 4  3  5]
 [10 10 10]
 [15 17 16]
 [10  5  5]]
5. Matrix is viable



## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".

  In conclusion, the activity covered the matrix in Python, including the row and column
matrices, square matrices, null matrix, zero matrix, ones matrix, diagonal matrix, identity
matrix, upper and lower triangular matrix and matrix algebra. We’ve gained the knowledge of
stating the shape and rank of a matrix and whether it is a square, zero, one or identity matrix
using if statements. We also learned about the try and except coding where it will ignore the
error of the code and print out the input that is correlated to the except code. As result, the code
will determine the shape and rank and whether the matrix is a square, zero, one or identity and
if it is null in task 1 and for task 2, when a matrix is not viable for operations, it will print out
“Matrix is not viable”.

- How can matrix operations solve problems in technology?

Matrix operations are used to provide rapid answers to more complex calculations.
They were initially created to describe systems of linear equations. You can use this in
encryption, economics and business, physics, animation, and many more. Matrices can also be
used to represent real world data like the population of people, infant mortality rate, etc. They
are the best representation methods for plotting surveys.