<a href="https://colab.research.google.com/github/Shamana027/Linear_Algebra_ChE_2nd-sem-2020-2021/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Operations

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition


$$A = \begin{bmatrix} 2 & 4 & 6\\-3 & 6 &9 \\ 5 & 0 & 1\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 2 & -3 & 5\\4 & 6 & 0 \\6 & 9 & 1\end{bmatrix} $$

In [ ]:
A = np.array([
    [3 ,1, 6, 8],
    [6, -9, -2, 5],
    [2, 4, 7, -7],
    [3, 6, 9, -12]
])
A

array([[  3,   1,   6,   8],
       [  6,  -9,  -2,   5],
       [  2,   4,   7,  -7],
       [  3,   6,   9, -12]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[  3,   6,   2,   3],
       [  1,  -9,   4,   6],
       [  6,  -2,   7,   9],
       [  8,   5,  -7, -12]])

In [ ]:
AT2 = A.T
AT2

array([[  3,   6,   2,   3],
       [  1,  -9,   4,   6],
       [  6,  -2,   7,   9],
       [  8,   5,  -7, -12]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [3 ,6, 9, 12],
    [2, -4, -6, 8],
    [1, 2, 3, -5]
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.shape

(4, 3)

## Dot Product / Inner Product

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [3,2,1],
    [3,6,9],
    [2,4,8]
])
Y = np.array([
    [8,4,-2],
    [1,3,6],
    [5,3,7]
])

In [ ]:
np.array_equiv(X, Y)

False

In [ ]:
np.dot(X,Y)

array([[31, 21, 13],
       [75, 57, 93],
       [60, 44, 76]])

In [ ]:
X.dot(Y)

array([[31, 21, 13],
       [75, 57, 93],
       [60, 44, 76]])

In [ ]:
X @ Y

array([[31, 21, 13],
       [75, 57, 93],
       [60, 44, 76]])

In [ ]:
np.matmul(X,Y)

array([[31, 21, 13],
       [75, 57, 93],
       [60, 44, 76]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
    [9, 11],
    [5, 3],
    [2, -7]
])
B = np.array([
    [-1,9],
    [-5, 5],
    [6,2]
])
C = np.array([
    [3,3,3],
    [5,10,15]
])

print(A.shape)
print(B.shape)
print(C.shape)


(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ C

array([[ 82, 137, 192],
       [ 30,  45,  60],
       [-29, -64, -99]])

In [ ]:
B @ C

array([[ 42,  87, 132],
       [ 10,  35,  60],
       [ 28,  38,  48]])

In [ ]:
C @ C.T

array([[ 27,  90],
       [ 90, 350]])

In [ ]:
A.T @ B

array([[-22, 110],
       [-68, 100]])

In [ ]:
A @ B

ValueError: ignored

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[ 90,  10,  76],
       [ 22, -10,  36],
       [-65, -45,  -2]])

Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [11,22,33],
    [10,20,30],
    [1,2,3]
])
B = np.array([
    [9,5,1],
    [5,3,4],
    [1,1,7]
])
C = np.array([
    [10,24,27],
    [5,15,25],
    [3,11,19]
])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(np.eye(3))

array([[11., 22., 33.],
       [10., 20., 30.],
       [ 1.,  2.,  3.]])

In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
E = A @ (B @ C)
E

array([[ 4180, 11748, 16654],
       [ 3800, 10680, 15140],
       [  380,  1068,  1514]])

In [ ]:
F = (A @ B) @ C
F

array([[ 4180, 11748, 16654],
       [ 3800, 10680, 15140],
       [  380,  1068,  1514]])

In [ ]:
np.array_equal(E, X)

False

In [ ]:
np.array_equiv(E, F)

True

In [ ]:
np.eye(A)

TypeError: ignored

In [ ]:
A @ E

array([[142120, 399432, 566236],
       [129200, 363120, 514760],
       [ 12920,  36312,  51476]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [9,3],
    [4,4],
])
np.linalg.det(A)

24.000000000000004

In [ ]:
B = np.array([
    [3,6,4],
    [5,5,1],
    [8,3,6]
])
np.linalg.det(B)

-151.0

In [ ]:
C = np.array([
    [1,2,3,4],
    [9,8,7,6],
    [4,3,2,1],
    [6,7,8,9]
])
np.linalg.det(C)

0.0

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [1,2],
    [-3, 4]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [3, 2, 2],
              [5, -3, 8],
              [2, 1, 5]
])
Q = np.linalg.inv(P)
Q


array([[ 0.35384615,  0.12307692, -0.33846154],
       [ 0.13846154, -0.16923077,  0.21538462],
       [-0.16923077, -0.01538462,  0.29230769]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -7.97972799e-17,  0.00000000e+00],
       [ 4.44089210e-16,  1.00000000e+00,  0.00000000e+00],
       [ 8.32667268e-17, -5.20417043e-18,  1.00000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate wether if the matrix that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

np.array([])

array([], dtype=float64)

In [ ]:
A = np.array([
        [6,-1,3,4],
        [0,9,-2,7],
        [1,8,-6,1],
        [-5,-3,3,2]
])

B = np.array([
        [1,1,1,1],
        [2,2,2,2],
        [3,3,3,3],
        [4,4,4,4]
])

C = np.array([
        [4,-7,5,2],
        [9,1,-1,3],
        [5,-7,4,-2],
        [0,-3,6,8]
])

I = np.eye(4)


In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
Q = A @ (B @ C)
Q

array([[ 522, -464,  406,  319],
       [ 720, -640,  560,  440],
       [  54,  -48,   42,   33],
       [ 108,  -96,   84,   66]])

In [ ]:
W = (A @ B) @ C
W

array([[ 522, -464,  406,  319],
       [ 720, -640,  560,  440],
       [  54,  -48,   42,   33],
       [ 108,  -96,   84,   66]])

In [ ]:
np.array_equal(Q, W)

True

In [ ]:
E = A @ (B + C)
E

array([[ 59, -47,  96,  64],
       [111,  42,  65, 127],
       [ 49,  43, -18,  49],
       [-26,  11,   8,  -3]])

In [ ]:
R = A @ B + A @ C
R

array([[ 59, -47,  96,  64],
       [111,  42,  65, 127],
       [ 49,  43, -18,  49],
       [-26,  11,   8,  -3]])

In [ ]:
np.array_equal(E, R)

True

In [ ]:
T = (B + C) @ A
T

array([[ 21, -20,   0, -10],
       [ 42,   9,  36,  76],
       [ 50,   9,  -7,  13],
       [-26,  49, -14,  57]])

In [ ]:
Y = B @ A + C @ A
Y

array([[ 21, -20,   0, -10],
       [ 42,   9,  36,  76],
       [ 50,   9,  -7,  13],
       [-26,  49, -14,  57]])

In [ ]:
np.array_equal(T, Y)

True

In [ ]:
A @ Q

array([[ 3006, -2672,  2338,  1837],
       [ 7128, -6336,  5544,  4356],
       [ 6066, -5392,  4718,  3707],
       [-4392,  3904, -3416, -2684]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
M = A @ I
M


array([[ 6., -1.,  3.,  4.],
       [ 0.,  9., -2.,  7.],
       [ 1.,  8., -6.,  1.],
       [-5., -3.,  3.,  2.]])

In [ ]:
N = I @ A
N

array([[ 6., -1.,  3.,  4.],
       [ 0.,  9., -2.,  7.],
       [ 1.,  8., -6.,  1.],
       [-5., -3.,  3.,  2.]])

In [ ]:
np.array_equal(N, M)

True

### Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. 

In conclusion, the activity covered the 6 Matrix Operations in Python; commutative
propery, associative property, distributive property, multiplicative identity property and
multiplicative property of zero. We have learned that commutative does not apply, rather, the
opposite occur where AB is not equal to BA and the other operations is still the same in
multiplication operations. We needed to prove and implement, by encoding whether the 6
matrix operations is true or not. The code will determine if the equation for the operation is
equal or not and as a result, all operations are equal except for the commutative propery.